### PR TITLE
NVC workflow

### PR DESCRIPTION
**Pull request by amb5l**
This PR adds a workflow to test OSVVM using the NVC simulator (both CTI and VTI tests). Results are uploaded as with GHDL, and a final check is performed so that the workflow will fail if any test failures have occurred. At the moment the workflow is manually triggered. Please review TODO items in the YAML file.

### CODE REVIEW

**Review by umarcor — COMMENTED** [review]
I would suggest to keep this PR as a draft, until the TODOs are solved and the content (job) can be added to the existing workflow.

**Comment by JimLewis** [comment]
I see two TODO's:
# TODO: change fetch-depth to 1 when OSVVM-Scripts master includes NVC support
# TODO remove this when NVC support exists in OSVVM-Scripts master

NVC support is already in Dev.

This will be pulled to Dev before going to main.    So maybe @amb5l you can updated the scripts to assume that they will be running against Dev and do the fetch-depth of 1 and also not fetch the Scripts directory later.   

I will be releasing 2022.10 sometime this week.   If I can pull this into Dev before then, it will be part of that.   If not, I will pull it shortly after and merge it into main then.

**Comment by amb5l** [comment]
@JimLewis There are a couple of other TODOs:
- TODO enable other events and/or schedule as required - I suggest that you take care of this
- TODO install from official MSYS2 package when available - NVC is currently installed from a binary hosted by its author on his personal website but going through the MSYS2 package process; when complete it will be available for all 3 64-bit environments of MSYS2

I will have a go at moving my changes to dev and removing the TODOs you listed. Please excuse me if things get messy, I am a novice when it comes to Git.

**Comment by amb5l** [comment]
Apologies - my force push closed this PR. I have pushed the new workflow with those 2 TODOs removed, and the checkout set to OsvvmLibraries' dev branch. It's in the dev branch of my fork now. @JimLewis please take a look and let me know if you need anything else?

**Comment by JimLewis** [comment]
@amb5l    I don't see any open pull requests from you.

**Pull request closed without merging**
