### PR TITLE
Added VideoBus submodule

### PR DESCRIPTION
**Pull request by Louadria**
I have created VideoBus receive and transmit Verification Components and would like to share them with anyone who might find them useful. The code is available at https://github.com/Louadria/VideoBus. 

VideoBus is a simple protocol to stream video using fval (frame valid) / lval (line valid) / dval (data valid). The library has a configurable number of data streams, in case multiple pixels are sent per cycle. 

I have made an example testbench using OSVVM showing how to use the VideoBusRx and VideoBusTx VCs using a simple passthrough DUT. The testbench also includes a bitmap logger for visual inspection. 

I hope you may find these useful, and please let me know if you have any comments or would like to change some things.

### CODE REVIEW

**Comment by JimLewis** [comment]
@Louadria  Apologies for not approving the pull yet.   I need to review it and I have been crazy busy the last couple of weeks.   Should be approved soon.

Jim

**Comment by JimLewis** [comment]
@Louadria  Is this for a standard interface or something that is commonly available on some dev board?

**Comment by Louadria** [comment]
It is an interface that is very commonly used (or a variant thereof) in video streaming

**Comment by JimLewis** [comment]
I talked to a colleague about this, when he saw video bus, he immediately thought of a high performance interface such as AxiStream with video transferred across it.   I tend to agree with his perspective.

 OTOH, what I see in your interface is looks just like the old TV interface (from my day), so I did a search on LCD interfaces. 
 I found several relevant links:
https://focuslcds.com/rgb-signals-and-timing-diagrams/
https://crystal-display.com/interfacing-lcd-panels-to-lcd-controllers/
https://www.nxp.com/wcm_documents/techzones/microcontrollers-techzone/Presentations/graphics.lcd.technologies.pdf

What I note in each of these is that they use the signal names:
VSync
HSync
DataEnable 
Data

If you agree that these represent what your VC is targeting since all three documents use these names, maybe these names would be better names than what you are using.   Also there is no need to prefix the names.

WRT the VC names, your VideoBusTx seems to match up with a DisplayController.   Your VideoBusRx seems to match up with a Display (or LcdDisplay).   There may be more suitable VC names than what I am thinking.   

One thing that is on my todo list for OSVVM is to add a string capability to the OSVVM record so that instead of passing pixels or bursts of pixels, that instead we pass a file name and the information is read from the file - such as your BMP file reader.   

To support your VC I would be willing to work on the file passing stuff to make that easy.   There are a couple of ways of doing it.

**Comment by vermaete** [comment]
@JimLewis 

The videobus of Louis is common used to connect rather simple video blocks in a pipe.
The signals are derived from the CameraLink standard.  What's rather common in industrial cameras.
See: https://www.imagelabs.com/wp-content/uploads/2010/10/CameraLink5.pdf chapter2.

The big difference with video with HSYNC, VSYNC, ... is that there is not real video timings involved.
So no front porch, back porch, blanking video.

IMHO is the signal naming of Louis correct and common used.

I hope this answers a few of you questions.

@Louadria Will you still find time to complete this MR?

**Comment by Louadria** [comment]
@vermaete I have made 2 pull requests (https://github.com/Louadria/VideoBus/pull/6 and https://github.com/Louadria/VideoBus/pull/5) that should fix the open issues.

**Comment by JimLewis** [comment]
@vermaete  I agree.   Thanks for the pdf link.
@Louadria  
I recommend adding stating that your VC implements the CameraLink standard in the README and provide a link to the pdf @vermaete showed.    Just knowing it was Video did not help me find the information.

Going further, it looks like there is little difference between CameraLink and the VSync, HSync, DataEnable timing of the documents I referenced.   If this is correct and your VC can implement the VSync, HSync, and DataEnable timing also, you might want to point that out in your documentation and make an association between the signals.   Putting the prefix "vid_" in the port names does not add value.   I generally try to make port names match the standard.   I like putting the _out /_in on them.   Some shorten it to _i and _o, but at this point we all grew up typing, so I like conventions that are clear to everyone.

**Comment by JimLewis** [comment]
Hi Louis
Sorry this has been taking so long.   I have a small amount of time the next couple of days and I hope to fork this and then included the forked repository in the OSVVM repository.   My colleague reminded me that included repositories will be of the form, <repositoryname>_<authorname>.  

The name can be one of the following or one you suggest:
VideoBus_Louadria
VideoBus_LouisAdriaens

Cheers,
Jim

**Comment by Louadria** [comment]
Hi Jim,

No problem. When you have time, just let me know if the open pull requests (https://github.com/Louadria/VideoBus/pull/6 and  https://github.com/Louadria/VideoBus/pull/5) are okay for you. The README has also been updated to include your suggestions. 

The name VideoBus_LouisAdriaens sounds good. 

Kind regards, 
Louis

**Comment by JimLewis** [comment]
I have done this an alternative way - which I believe helps as if your account goes away, we still have the VideoBus repository:
I cloned your VideoBus Repository into the OSVVM project.
Then I included the cloned VideoBus Repository in the OsvvmLibraries distribution.

**Pull request closed without merging**
