### PR TITLE
authors: merge content of 'CONTRIBUTORS.md' to avoid duplication

### PR DESCRIPTION
**Pull request by umarcor**
Currently, the content of `AUTHORS.md` and `CONTRIBUTORS.md` is mostly duplicated. This PR merges the content into `AUTHORS.md` and replaces the content of `CONTRIBUTORS.md` with a reference to the former.

### CODE REVIEW

**Comment by JimLewis** [comment]
@umarcor   This is an IEEE and/or Josh thing.   

Authors are to acknowledge the copyright holders - for example all the work I do is copyrighted by SynthWorks Design Inc.    

Contributors, may be optional, is to acknowledge the people who contributed -whether they own their work or not.

**Comment by JimLewis** [comment]
I was not able to understand what you did in the differences view.   However, I just figured out how to see it in the view that led me to your repository.    Honestly, I am not sure.   I think by having Authors might form some sort of legal definition.

I can ask Josh if it is ok.  

OTOH, feel free to edit the contributing process.

Also we can add your name to the files as a contributor (and CI wizard).

**Comment by umarcor** [comment]
@JimLewis I expected that to be the reason. That's why I created this PR with a single commit, instead of having this mixed with other PRs.

The point is, I can understand the requirement for files CONTRIBUTORS.md and AUTHORS.md to exist. I don't agree with it being a requirement, but I understand if someone sets that rule. However, I believe it is nonsense to duplicate exactly the same content. Therefore, all I did in this PR was the distinct information from CONTRIBUTORS.md (that is, the list of contributors) and add it as a subsection in AUTHORS.md: https://github.com/umarcor/OsvvmLibraries/blob/contrib-merge/AUTHORS.md. No information was removed, no information was added. However, now the "Participating" section is not duplicated in both document, which reduces the maintenance burden and ensures that there is no sync problem.

> I was not able to understand what you did in the differences view. However, I just figured out how to see it in the view that led me to your repository. Honestly, I am not sure. I think by having Authors might form some sort of legal definition.

That's probably the best way to see it. As commented, the information is the same:

- Current list of authors: https://github.com/OSVVM/OsvvmLibraries/blob/master/AUTHORS.md#osvvm-project-authors---the-people-andor-organizations-who-own-the-copyrights
- Current list of contributors: https://github.com/OSVVM/OsvvmLibraries/blob/master/CONTRIBUTORS.md#osvvm-project-contributors---the-people-who-contribute-to-osvvm.
- Proposed list with a subsection for authors and a subsection for contributors: https://github.com/umarcor/OsvvmLibraries/blob/contrib-merge/AUTHORS.md#osvvm-project-authors-and-contributors

- Currently duplicated participating info: https://github.com/OSVVM/OsvvmLibraries/blob/master/AUTHORS.md#participating and https://github.com/OSVVM/OsvvmLibraries/blob/master/CONTRIBUTORS.md#participating
- Proposed single location: https://github.com/umarcor/OsvvmLibraries/blob/contrib-merge/AUTHORS.md#participating

> Authors are to acknowledge the copyright holders - for example all the work I do is copyrighted by SynthWorks Design Inc.
> Contributors, may be optional, is to acknowledge the people who contributed -whether they own their work or not.

While I understand the intent (that is explained in the headers), I believe that the terms are not correct. Contributors are authors by definition (in legal terms) and they own the copyright of their own work. However, they also license it to the project (OSVVM) and they might explicitly grant the gatekeeper (SynthWorks) full control over what to do with their code contributions. This might not be true in all the countries in the world, but it's is in a number of them, enough for it being relevant. The difference between authors and contributors in practice is related to the responsability they take and how much of the project they wrote/maintain, which is unrelated to holding the copyright.

Anyway, it is not my purpose to modify the content. Currently the same people are listed both as authors and contributors. I did not change that.

**Comment by umarcor** [comment]
@JimLewis did you ask Josh about this?

**Comment by JimLewis** [comment]
@umarcor  Never discussed this with Josh.    OTOH, I pointed out issues with other repositories to Josh regarding invalid and improper copyrights on an IEEE site.   That was August 2022.   No action by December 2022.   So apparently for bigger items than this, they really don't care, so I decided this was up to me and I like the briefer form you suggested.

**Pull request merged**
